stages:
- stage: Integration
  condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'ResourceTrigger'))
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  # Integration Test Jobs
  - template: ../Jobs/integration.yml